language: 
  node_js
node_js:
  - 0.8
branches:
  only:
    - master
env:
  global:
    - secure: "ZMqyhEGxTPx25aTCD5b0uMNs1rbbWfCy2GmHVuJZ7qph/gkA8N1qz0ko3E1a\ncA9gwMngbhlq/+YQrmvuvgPkEtYNZCuzPibUDATQdHcEZPSI4r4JRFdk9kTG\ncTCrubDQNXsdZ79NdcNsXyY45PiGDLTmnFQWucYgjuD6q2MlR20="
before_script:
  - gem install compass
  - ./node_modules/.bin/bower install
script: 
  - ./node_modules/.bin/yeoman build --disable-insight
after_script:
  - git config --global user.email "pwmckenna@gmail.com"
  - git config --global user.name "Patrick Williams"
  - git push https://${GH_TOKEN}@github.com/pwmckenna/mduel :gh-pages > /dev/null 2>&1
