language: 
  node_js
node_js:
  - 0.8
branches:
  only:
    - master
env:
  global:
    - secure: "ZMqyhEGxTPx25aTCD5b0uMNs1rbbWfCy2GmHVuJZ7qph/gkA8N1qz0ko3E1a\ncA9gwMngbhlq/+YQrmvuvgPkEtYNZCuzPibUDATQdHcEZPSI4r4JRFdk9kTG\ncTCrubDQNXsdZ79NdcNsXyY45PiGDLTmnFQWucYgjuD6q2MlR20="
before_script:
  - gem install compass
  - ./node_modules/.bin/bower install
after_script:
  - ./node_modules/.bin/yeoman build --disable-insight
  - git config --global user.email "pwmckenna@gmail.com"
  - git config --global user.name "Patrick Williams"
  - git submodule add -b gh-pages https://${GH_TOKEN}@github.com/pwmckenna/mduel site
  - cd site
  - git checkout gh-pages
  - git rm -r .
  - cp -R ../dist/* .
  - git add -f .
  - git commit -am "adding the yeoman build files to gh-pages"
  - git push https://${GH_TOKEN}@github.com/pwmckenna/mduel gh-pages > /dev/null 2>&1
