language: 
  node_js
node_js:
  - 0.8
branches:
  only:
    - master
env:
  global:
    # GH_TOKEN is the oauth token generated as described at https://help.github.com/articles/creating-an-oauth-token-for-command-line-use
    - secure: "ZMqyhEGxTPx25aTCD5b0uMNs1rbbWfCy2GmHVuJZ7qph/gkA8N1qz0ko3E1a\ncA9gwMngbhlq/+YQrmvuvgPkEtYNZCuzPibUDATQdHcEZPSI4r4JRFdk9kTG\ncTCrubDQNXsdZ79NdcNsXyY45PiGDLTmnFQWucYgjuD6q2MlR20="
    - GH_USER: pwmckenna
    - GH_PROJECT: mduel
    - GH_NAME: Patrick Williams
    - GH_EMAIL: pwmckenna@gmail.com

before_script:
  # install dependencies
  - gem install compass
  - gem install jpegtran
  - gem install optipng
  - npm install bower -g
  - npm install yeoman -g
  - bower install
script:
  - yeoman test
  - yeoman build --disable-insight
after_script:
  - git config --global user.email "${GH_EMAIL}"
  - git config --global user.name "${GH_NAME}"
  - git submodule add -b gh-pages https://${GH_TOKEN}@github.com/${GH_USERNAME}/${GH_PROJECT} site
  - cd site
  - git checkout gh-pages
  - git rm -r .
  - cp -R ../dist/* .
  - cp ../dist/.* .
  - git add -f .
  - git commit -am "adding the yeoman build files to gh-pages"
  - git push https://${GH_TOKEN}@github.com/${GH_USERNAME}/${GH_PROJECT} gh-pages > /dev/null 2>&1
